#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=48:00:00
#PBS -o logs/job.out
#PBS -e logs/job.err
NCPU=`wc -l < $PBS_NODEFILE`
NNODES=`uniq $PBS_NODEFILE | wc -l`
cd $PBS_O_WORKDIR

mpirun -n ${NCPU} /opt/amber14/bin/sander.MPI -O -i md_inputs/3_eq-so2.in -o md_outputs/3_eq-so2.out -p md_inputs/water_so2.prmtop -c checkpoints/2_eq+so2.rst -r checkpoints/3_eq-so2.rst -ref md_inputs/water_so2.inpcrd -x ptraj/3_eq-so2.mdcrd 
