#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=48:00:00
#PBS -o logs/job.out
#PBS -e logs/job.err
echo $PBS_NODEFILE
NCPU=`wc -l < $PBS_NODEFILE`
NNODES=`uniq $PBS_NODEFILE | wc -l`

cd $PBS_O_WORKDIR
mpirun -n ${NCPU} /opt/amber14/bin/sander.MPI -O -i md_inputs/3_production.in -o md_outputs/production.out -p md_inputs/water_solvated.prmtop -c checkpoints/2_eq.rst -r checkpoints/3_production.rst -x ptraj/production.mdcrd

